# -*- coding: utf-8 -*-
"""Sentimental_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlGgvJAPp7CykEJrwjp4A3G2nzXYZTRq
"""

! pip install googletrans==3.1.0a0

pip install TextBlob

from textblob import TextBlob
from googletrans import Translator # for language translation
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from transformers import pipeline

#download vader lexicon
nltk.download('vader_lexicon') # valence aware dictionary and sentiment analysis
#initialize tools
translator = Translator()
vader_analyzer = SentimentIntensityAnalyzer()
transformer_analyzer = pipeline("sentiment-analysis")
#Input text (Ensure it's synchronous)
text = input("Enter text in Hindi , Marathi, or English for sentiment analysis:")
#Detect language and translate if neccesary
translated_text = translator.translate(text,src='auto',dest='en').text
print(f"Original Text: {text}")
print(f"Translate Text (to English): {translated_text}")
#TexBlob Sentiment Analysis
blob = TextBlob(translated_text)
blob_polarity = blob.sentiment.polarity # Polarity: -1 (-ve) to 1 (+ve)
blob_subjectivity = blob.sentiment.subjectivity # subjectively: 0(objective) to 1 (subjective)
print("\nTextBlob Sentiment Analysis:")
print(f"Polarity:{blob_polarity}")
print(f"Subjectivity:{blob_subjectivity}")

#VADER Sentiment Analysis
vader_scores = vader_analyzer.polarity_scores(translated_text)

print("\nVADER Sentiment Analysis:")
print(f"Positive:{vader_scores['pos']}")
print(f"Neutral:{vader_scores['neu']}")
print(f"Negative:{vader_scores['neg']}")
print(f"Compound Score:{vader_scores['compound']}")
#overall Interpretation
if vader_scores['compound'] >=0.05:
  overall_sentiment = "Positive"
elif vader_scores['compound'] <=0.05:
  overall_sentiment = "Negative"
else:
  overall_sentiment = "Neutral"

print(f"\nOverall Sentiment (VADER): {overall_sentiment}")

 #advanced sentiment analysis using hugging face transformer
transformer_result = transformer_analyzer(translated_text)

print("Transformers Sentiment Analysis:")
print(f"Label:{transformer_result[0]['label']}")
print(f"Score: {transformer_result[0]['score']}")

